kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # the default CNI will not be installed
  #disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true" # node affinity for ingress-nginx controll sample
    # extraPortMappings:      # for windows/mac
    #   - containerPort: 80
    #     hostPort: 80
    #     protocol: TCP
    #   - containerPort: 443
    #     hostPort: 443
    #     protocol: TCP
  - role: worker